# Generated by Django 4.1 on 2022-08-18 21:07

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 21, 7, 5, 192107), validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 8, 18, 21, 7, 5, 192110))]),
        ),
        migrations.AlterField(
            model_name='operator',
            name='index',
            field=models.IntegerField(unique=True),
        ),
    ]
