# Generated by Django 4.1 on 2022-08-19 06:48

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_mailing_start_date_alter_operator_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['status']},
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_sent',
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.operator'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 19, 6, 47, 34, 780488), validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 8, 19, 6, 47, 34, 780491))]),
        ),
        migrations.AlterField(
            model_name='message',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.customer'),
        ),
        migrations.AlterField(
            model_name='message',
            name='mailing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.mailing'),
        ),
    ]
