# Generated by Django 4.1 on 2022-08-22 12:17

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_message_options_remove_message_is_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.RegexValidator('^7/d/d/d/d/d/d/d/d/d/d')]),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 12, 17, 5, 358733), validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 8, 22, 12, 17, 5, 358736))]),
        ),
    ]
