# Generated by Django 4.1 on 2022-08-22 12:21

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_customer_phone_alter_mailing_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 12, 21, 43, 717932, tzinfo=datetime.timezone.utc), validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 8, 22, 12, 21, 43, 717936, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='stop_date',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 8, 22, 12, 21, 43, 717950, tzinfo=datetime.timezone.utc))]),
        ),
    ]
