# Generated by Django 4.1 on 2022-08-22 12:25

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_alter_mailing_start_date_alter_mailing_stop_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.RegexValidator('7/d/d/d/d/d/d/d/d/d/d')]),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 12, 25, 17, 729716, tzinfo=datetime.timezone.utc), validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 8, 22, 12, 25, 17, 729721, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='stop_date',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 8, 22, 12, 25, 17, 729735, tzinfo=datetime.timezone.utc))]),
        ),
    ]
