# Generated by Django 4.1 on 2022-08-22 21:14

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_alter_customer_phone_alter_mailing_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='index',
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.RegexValidator('^7([0-9]{10})', 'It must be in form 7XXXXXXXXXX.')]),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 21, 14, 44, 552145, tzinfo=datetime.timezone.utc), validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 8, 22, 21, 14, 44, 552151, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='stop_date',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 8, 22, 21, 14, 44, 552165, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='operator',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
