# Generated by Django 4.1 on 2022-08-22 23:14

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_remove_operator_index_alter_customer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mailing',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 23, 14, 28, 55939, tzinfo=datetime.timezone.utc), validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 8, 22, 23, 14, 28, 55944, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='stop_date',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 8, 22, 23, 14, 28, 55957, tzinfo=datetime.timezone.utc))]),
        ),
    ]
