# Generated by Django 4.1 on 2022-08-23 01:12

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0009_mailing_is_completed_mailing_is_started_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 23, 1, 12, 23, 242699, tzinfo=datetime.timezone.utc), validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 8, 23, 1, 12, 23, 242704, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='stop_date',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 8, 23, 1, 12, 23, 242717, tzinfo=datetime.timezone.utc))]),
        ),
    ]
